import {
  Truck,
  Trailer,
  Driver,
  MaintenanceRecord,
  TruckShop,
} from "@/types/fleet";

export const initialTrucks: Truck[] = [
  {
    id: "truck-101",
    unitNumber: "101",
    make: "Freightliner",
    model: "Cascadia 126",
    year: 2023,
    vin: "1FUJGHDV8PL129841",
    plateNumber: "P398102",
    isTemporaryPlate: false,
    ownershipType: "Own",
    truckValue: 138000,
    bestPassSerialNumber: "BP-9938102",
    isBestPassLinked: true,
    assignedDriverId: "driver-1",
    status: "Active",
    currentMileage: 142500,
    notes: "Assigned to dedicated Midwest - Southeast route. APU serviced last month.",
    documents: {
      title: {
        id: "doc-t101-title",
        name: "Title_Truck_101.pdf",
        category: "Title",
        fileType: "application/pdf",
        fileSize: 420000,
        uploadedAt: "2023-04-12T10:00:00Z",
        notes: "Clean title held by Zdunje Trucking LLC",
      },
      tax2290: {
        id: "doc-t101-2290",
        name: "Form_2290_Schedule1_2026.pdf",
        category: "2290",
        fileType: "application/pdf",
        fileSize: 310000,
        uploadedAt: "2026-07-02T09:15:00Z",
        expirationDate: "2027-06-30",
        notes: "IRS watermarked e-file receipt",
      },
      dotInspection: {
        id: "doc-t101-dot",
        name: "Annual_DOT_Inspection_101.pdf",
        category: "DOT Inspection",
        fileType: "application/pdf",
        fileSize: 520000,
        uploadedAt: "2025-10-25T14:30:00Z",
        expirationDate: "2026-10-25", // Upcoming alert within 30 days!
        notes: "Passed with zero defects at TA Lake Station",
      },
      insurance: {
        id: "doc-t101-ins",
        name: "Bobtail_PhysicalDamage_101.pdf",
        category: "Bobtail Insurance / Physical Damage",
        fileType: "application/pdf",
        fileSize: 680000,
        uploadedAt: "2026-01-10T11:00:00Z",
        expirationDate: "2027-01-10",
        notes: "Northland Insurance - $1M Combined Single Limit",
      },
      cabCard: {
        id: "doc-t101-cab",
        name: "IRP_CabCard_101.pdf",
        category: "CABCard",
        fileType: "application/pdf",
        fileSize: 340000,
        uploadedAt: "2026-02-15T08:00:00Z",
        expirationDate: "2027-02-28",
        notes: "Apportioned registration all 48 lower states",
      },
      leaseAgreement: {
        id: "doc-t101-lease",
        name: "Internal_Equipment_Agreement_101.pdf",
        category: "Lease Agreement",
        fileType: "application/pdf",
        fileSize: 450000,
        uploadedAt: "2023-04-15T12:00:00Z",
        notes: "Zdunje Trucking internal asset schedule",
      },
    },
  },
  {
    id: "truck-104",
    unitNumber: "104",
    make: "Kenworth",
    model: "T680 Next Gen",
    year: 2022,
    vin: "1XKYDP9X6NJ209182",
    plateNumber: "TEMP-88319",
    isTemporaryPlate: true,
    ownershipType: "Lease",
    truckValue: 122000,
    bestPassSerialNumber: "BP-4491021",
    isBestPassLinked: true,
    assignedDriverId: "driver-2",
    status: "Active",
    currentMileage: 189200,
    notes: "Temporary plate active while Illinois DMV processes permanent plate transfer.",
    documents: {
      title: null,
      tax2290: {
        id: "doc-t104-2290",
        name: "Form_2290_2026_Unit104.pdf",
        category: "2290",
        fileType: "application/pdf",
        fileSize: 280000,
        uploadedAt: "2026-07-05T10:00:00Z",
        expirationDate: "2027-06-30",
      },
      dotInspection: {
        id: "doc-t104-dot",
        name: "Annual_DOT_104.pdf",
        category: "DOT Inspection",
        fileType: "application/pdf",
        fileSize: 490000,
        uploadedAt: "2026-03-14T16:00:00Z",
        expirationDate: "2027-03-14",
      },
      insurance: {
        id: "doc-t104-ins",
        name: "Certificate_Insurance_104.pdf",
        category: "Bobtail Insurance / Physical Damage",
        fileType: "application/pdf",
        fileSize: 620000,
        uploadedAt: "2026-01-10T11:00:00Z",
        expirationDate: "2027-01-10",
      },
      cabCard: {
        id: "doc-t104-cab",
        name: "Temporary_Registration_Permit_104.pdf",
        category: "CABCard",
        fileType: "application/pdf",
        fileSize: 210000,
        uploadedAt: "2026-09-01T09:00:00Z",
        expirationDate: "2026-10-15", // Urgent alert!
        notes: "45-day temporary permit",
      },
      leaseAgreement: {
        id: "doc-t104-lease",
        name: "PACCAR_Lease_Agreement_104.pdf",
        category: "Lease Agreement",
        fileType: "application/pdf",
        fileSize: 890000,
        uploadedAt: "2022-05-01T10:00:00Z",
      },
    },
  },
  {
    id: "truck-107",
    unitNumber: "107",
    make: "Peterbilt",
    model: "579 UltraLoft",
    year: 2024,
    vin: "1XPBD49X1RD309812",
    plateNumber: "TRK-4912",
    isTemporaryPlate: false,
    ownershipType: "Own",
    truckValue: 165000,
    bestPassSerialNumber: "BP-7719203",
    isBestPassLinked: false, // Attention needed
    assignedDriverId: null,
    status: "In Shop",
    currentMileage: 46200,
    notes: "Currently in shop for scheduled 45k service and BestPass transponder installation.",
    documents: {
      title: {
        id: "doc-t107-title",
        name: "Peterbilt_107_Title.pdf",
        category: "Title",
        fileType: "application/pdf",
        fileSize: 410000,
        uploadedAt: "2024-02-10T10:00:00Z",
      },
      tax2290: {
        id: "doc-t107-2290",
        name: "2290_2026_Schedule1_107.pdf",
        category: "2290",
        fileType: "application/pdf",
        fileSize: 315000,
        uploadedAt: "2026-07-01T08:00:00Z",
        expirationDate: "2027-06-30",
      },
      dotInspection: {
        id: "doc-t107-dot",
        name: "Annual_DOT_Peterbilt_107.pdf",
        category: "DOT Inspection",
        fileType: "application/pdf",
        fileSize: 510000,
        uploadedAt: "2026-02-12T11:00:00Z",
        expirationDate: "2027-02-12",
      },
      insurance: {
        id: "doc-t107-ins",
        name: "Physical_Damage_107.pdf",
        category: "Bobtail Insurance / Physical Damage",
        fileType: "application/pdf",
        fileSize: 590000,
        uploadedAt: "2026-01-10T11:00:00Z",
        expirationDate: "2027-01-10",
      },
      cabCard: {
        id: "doc-t107-cab",
        name: "CabCard_2026_107.pdf",
        category: "CABCard",
        fileType: "application/pdf",
        fileSize: 320000,
        uploadedAt: "2026-02-15T08:00:00Z",
        expirationDate: "2027-02-28",
      },
      leaseAgreement: null,
    },
  },
];

export const initialTrailers: Trailer[] = [
  {
    id: "trailer-5301",
    unitNumber: "TR-5301",
    make: "Great Dane",
    model: "Champion 53' Dry Van",
    year: 2022,
    vin: "1GRAN5320ND194821",
    plateNumber: "TL-78201",
    isTemporaryPlate: false,
    ownershipType: "Own",
    trailerValue: 44000,
    status: "Active",
    assignedTruckId: "truck-101",
    notes: "Equipped with aerodynamic side skirts and tire inflation system.",
    documents: {
      title: {
        id: "doc-tr5301-title",
        name: "Title_Trailer_5301.pdf",
        category: "Title",
        fileType: "application/pdf",
        fileSize: 390000,
        uploadedAt: "2022-06-10T10:00:00Z",
      },
      tax2290: null,
      dotInspection: {
        id: "doc-tr5301-dot",
        name: "DOT_Annual_TR5301.pdf",
        category: "DOT Inspection",
        fileType: "application/pdf",
        fileSize: 480000,
        uploadedAt: "2025-11-10T09:00:00Z",
        expirationDate: "2026-11-10",
      },
      insurance: {
        id: "doc-tr5301-ins",
        name: "Trailer_PhysicalDamage_5301.pdf",
        category: "Bobtail Insurance / Physical Damage",
        fileType: "application/pdf",
        fileSize: 550000,
        uploadedAt: "2026-01-10T11:00:00Z",
        expirationDate: "2027-01-10",
      },
      cabCard: {
        id: "doc-tr5301-cab",
        name: "Trailer_Registration_5301.pdf",
        category: "CABCard",
        fileType: "application/pdf",
        fileSize: 310000,
        uploadedAt: "2025-12-01T10:00:00Z",
        expirationDate: "2026-12-31",
      },
      trailerAgreement: {
        id: "doc-tr5301-agr",
        name: "Trailer_Operating_Agreement_5301.pdf",
        category: "Trailer Agreement",
        fileType: "application/pdf",
        fileSize: 360000,
        uploadedAt: "2022-06-15T14:00:00Z",
      },
    },
  },
  {
    id: "trailer-5308",
    unitNumber: "TR-5308",
    make: "Utility",
    model: "3000R 53' Reefer (ThermoKing S-600)",
    year: 2021,
    vin: "1UYVS2537MA209144",
    plateNumber: "TL-99120",
    isTemporaryPlate: false,
    ownershipType: "Lease",
    trailerValue: 71000,
    status: "Active",
    assignedTruckId: "truck-104",
    notes: "Thermo King Precedent reefer unit. Engine hours: 4,120 hrs.",
    documents: {
      title: null,
      tax2290: null,
      dotInspection: {
        id: "doc-tr5308-dot",
        name: "Annual_DOT_Reefer_5308.pdf",
        category: "DOT Inspection",
        fileType: "application/pdf",
        fileSize: 520000,
        uploadedAt: "2025-10-04T12:00:00Z",
        expirationDate: "2026-10-04", // Urgent expiration!
        notes: "Scheduled for renewal next week",
      },
      insurance: {
        id: "doc-tr5308-ins",
        name: "Trailer_Insurance_5308.pdf",
        category: "Bobtail Insurance / Physical Damage",
        fileType: "application/pdf",
        fileSize: 600000,
        uploadedAt: "2026-01-10T11:00:00Z",
        expirationDate: "2027-01-10",
      },
      cabCard: {
        id: "doc-tr5308-cab",
        name: "Registration_5308.pdf",
        category: "CABCard",
        fileType: "application/pdf",
        fileSize: 290000,
        uploadedAt: "2025-12-01T10:00:00Z",
        expirationDate: "2026-12-31",
      },
      trailerAgreement: {
        id: "doc-tr5308-agr",
        name: "Premier_Trailer_Lease_5308.pdf",
        category: "Trailer Agreement",
        fileType: "application/pdf",
        fileSize: 740000,
        uploadedAt: "2021-08-01T10:00:00Z",
      },
    },
  },
  {
    id: "trailer-5312",
    unitNumber: "TR-5312",
    make: "Wabash",
    model: "DuraPlate 53' Dry Van",
    year: 2023,
    vin: "1WABC5324PA310928",
    plateNumber: "TEMP-4410",
    isTemporaryPlate: true,
    ownershipType: "Own",
    trailerValue: 48000,
    status: "Available",
    assignedTruckId: null,
    notes: "Staged at Chicago terminal yard. Clean and ready for dispatch.",
    documents: {
      title: {
        id: "doc-tr5312-title",
        name: "Wabash_5312_Title.pdf",
        category: "Title",
        fileType: "application/pdf",
        fileSize: 370000,
        uploadedAt: "2023-08-20T10:00:00Z",
      },
      tax2290: null,
      dotInspection: {
        id: "doc-tr5312-dot",
        name: "DOT_Annual_5312.pdf",
        category: "DOT Inspection",
        fileType: "application/pdf",
        fileSize: 505000,
        uploadedAt: "2026-05-18T10:00:00Z",
        expirationDate: "2027-05-18",
      },
      insurance: {
        id: "doc-tr5312-ins",
        name: "Trailer_Physical_5312.pdf",
        category: "Bobtail Insurance / Physical Damage",
        fileType: "application/pdf",
        fileSize: 580000,
        uploadedAt: "2026-01-10T11:00:00Z",
        expirationDate: "2027-01-10",
      },
      cabCard: {
        id: "doc-tr5312-cab",
        name: "Temp_Registration_5312.pdf",
        category: "CABCard",
        fileType: "application/pdf",
        fileSize: 220000,
        uploadedAt: "2026-08-15T10:00:00Z",
        expirationDate: "2026-11-15",
      },
      trailerAgreement: null,
    },
  },
];

export const initialDrivers: Driver[] = [
  {
    id: "driver-1",
    firstName: "John",
    middleName: "David",
    lastName: "Miller",
    dateOfBirth: "1984-06-14",
    phone: "(312) 555-0182",
    state: "IL",
    licenseNumber: "M829-1048-2910",
    status: "Active",
    assignedTruckId: "truck-101",
    hireDate: "2021-04-15",
    notes: "Clean driving record. Preferred runner for Midwest to Atlanta corridor.",
    bankInfo: {
      accountNumber: "4829104829",
      routingNumber: "071000013",
      bankName: "Chase Bank",
    },
    documents: {
      mvr: {
        id: "doc-d1-mvr",
        name: "Annual_MVR_Miller_2026.pdf",
        category: "MVR",
        fileType: "application/pdf",
        fileSize: 340000,
        uploadedAt: "2026-04-10T09:00:00Z",
        notes: "Zero violations in 36-month lookback",
      },
      pspAuth: {
        id: "doc-d1-pspauth",
        name: "PSP_Consent_Authorization_Miller.pdf",
        category: "PSP Authorization",
        fileType: "application/pdf",
        fileSize: 210000,
        uploadedAt: "2021-04-10T10:00:00Z",
      },
      pspReport: {
        id: "doc-d1-psprep",
        name: "PSP_FMCSA_Report_Miller.pdf",
        category: "PSP Driver Report",
        fileType: "application/pdf",
        fileSize: 450000,
        uploadedAt: "2026-04-11T11:00:00Z",
        notes: "Score: 0 crashes, 0 safety violations",
      },
      cdl: {
        id: "doc-d1-cdl",
        name: "CDL_ClassA_Miller_IL.pdf",
        category: "CDL",
        fileType: "application/pdf",
        fileSize: 520000,
        uploadedAt: "2024-06-10T10:00:00Z",
        expirationDate: "2028-06-14",
        notes: "Class A Commercial Driver License with Tanker & Doubles endorsements",
      },
      medCard: {
        id: "doc-d1-med",
        name: "DOT_Medical_Examiner_Cert_Miller.pdf",
        category: "MEDCard",
        fileType: "application/pdf",
        fileSize: 380000,
        uploadedAt: "2024-10-18T14:00:00Z",
        expirationDate: "2026-10-18", // Expiration alert! Within 20 days
        notes: "Dr. Robert Hayes, NRCME # 992810. 2-year certification.",
      },
      clearingHouse: {
        id: "doc-d1-ch",
        name: "FMCSA_Clearinghouse_AnnualQuery_Miller.pdf",
        category: "Clearing House",
        fileType: "application/pdf",
        fileSize: 290000,
        uploadedAt: "2026-04-15T08:30:00Z",
        notes: "Status: Not Prohibited",
      },
      applicationLink: "https://intelli-app.zdunjetrucking.com/app/j-miller-829",
      applicationFile: {
        id: "doc-d1-app",
        name: "Driver_Application_Signed_Miller.pdf",
        category: "Application Link",
        fileType: "application/pdf",
        fileSize: 840000,
        uploadedAt: "2021-04-08T16:00:00Z",
      },
      drugCustodyForm: {
        id: "doc-d1-ccf",
        name: "Chain_Of_Custody_Form_Miller.pdf",
        category: "Drug Test Custody Form",
        fileType: "application/pdf",
        fileSize: 420000,
        uploadedAt: "2021-04-12T10:00:00Z",
      },
      drugPassport: {
        id: "doc-d1-pass",
        name: "Quest_ePassport_Miller.pdf",
        category: "Drug Test ePassport",
        fileType: "application/pdf",
        fileSize: 220000,
        uploadedAt: "2021-04-11T12:00:00Z",
      },
      drugTestResults: [
        {
          id: "doc-d1-dt-1",
          name: "DrugTest_PreEmployment_Miller.pdf",
          category: "Drug Test Result",
          fileType: "application/pdf",
          fileSize: 310000,
          uploadedAt: "2021-04-14T10:00:00Z",
          testDate: "2021-04-13",
          testType: "Pre-Employment",
          notes: "Result: NEGATIVE (5-panel DOT urine)",
        },
        {
          id: "doc-d1-dt-2",
          name: "DrugTest_Random_FMCSA_Q1_2025.pdf",
          category: "Drug Test Result",
          fileType: "application/pdf",
          fileSize: 295000,
          uploadedAt: "2025-03-18T15:00:00Z",
          testDate: "2025-03-17",
          testType: "Random FMCSA",
          notes: "Q1 Random pool selection. Result: NEGATIVE",
        },
        {
          id: "doc-d1-dt-3",
          name: "DrugTest_Random_FMCSA_Q3_2026.pdf",
          category: "Drug Test Result",
          fileType: "application/pdf",
          fileSize: 305000,
          uploadedAt: "2026-08-22T14:30:00Z",
          testDate: "2026-08-21",
          testType: "Random FMCSA",
          notes: "August FMCSA random pool selection. Result: NEGATIVE",
        },
      ],
      dotRecords: [
        {
          id: "doc-d1-dot-1",
          name: "Roadside_DOT_Inspection_Level3_Miller.pdf",
          category: "Driver DOT Record",
          fileType: "application/pdf",
          fileSize: 320000,
          uploadedAt: "2026-06-12T14:30:00Z",
          recordDate: "2026-06-12",
          inspectionLevel: "Level 3 (Driver-Only)",
          inspectionResult: "Clean / No Violations",
          notes: "Ohio State Highway Patrol I-80 scale inspection. Clean roadside inspection - zero violations.",
        },
      ],
      bankInfoDoc: {
        id: "doc-d1-bank",
        name: "Direct_Deposit_Authorization_Miller.pdf",
        category: "Bank Information",
        fileType: "application/pdf",
        fileSize: 310000,
        uploadedAt: "2021-04-15T11:00:00Z",
        notes: "Voided check attached for Chase Bank",
      },
      einLetter: {
        id: "doc-d1-ein",
        name: "W9_Form_Miller_Transport.pdf",
        category: "EIN Letter",
        fileType: "application/pdf",
        fileSize: 260000,
        uploadedAt: "2021-04-15T11:30:00Z",
        notes: "Miller Express LLC / EIN verified",
      },
      onboardingDoc: {
        id: "doc-d1-onboard",
        name: "Driver_Onboarding_Handbook_Miller.pdf",
        category: "Onboarding Document",
        fileType: "application/pdf",
        fileSize: 480000,
        uploadedAt: "2021-04-15T09:00:00Z",
        notes: "Company safety policies & driver handbook signed",
      },
      leaseAgreement: null,
    },
    skippedDocuments: ["leaseAgreement"],
  },
  {
    id: "driver-2",
    firstName: "Aleksandar",
    middleName: "Alex",
    lastName: "Petrovic",
    dateOfBirth: "1979-11-22",
    phone: "(219) 555-0194",
    state: "IN",
    licenseNumber: "IN-8291-0399-44",
    status: "Active",
    assignedTruckId: "truck-104",
    hireDate: "2022-09-01",
    notes: "Senior driver. Great maintenance habits and on-time safety inspections.",
    bankInfo: {
      accountNumber: "9102837461",
      routingNumber: "071921891",
      bankName: "Fifth Third Bank",
    },
    documents: {
      mvr: {
        id: "doc-d2-mvr",
        name: "MVR_Indiana_Petrovic_2026.pdf",
        category: "MVR",
        fileType: "application/pdf",
        fileSize: 320000,
        uploadedAt: "2026-08-10T10:00:00Z",
      },
      pspAuth: {
        id: "doc-d2-pspauth",
        name: "PSP_Signed_Consent_Petrovic.pdf",
        category: "PSP Authorization",
        fileType: "application/pdf",
        fileSize: 195000,
        uploadedAt: "2022-08-25T11:00:00Z",
      },
      pspReport: {
        id: "doc-d2-psprep",
        name: "FMCSA_PSP_Petrovic.pdf",
        category: "PSP Driver Report",
        fileType: "application/pdf",
        fileSize: 410000,
        uploadedAt: "2026-08-11T12:00:00Z",
      },
      cdl: {
        id: "doc-d2-cdl",
        name: "CDL_Indiana_Petrovic.pdf",
        category: "CDL",
        fileType: "application/pdf",
        fileSize: 540000,
        uploadedAt: "2023-11-01T09:00:00Z",
        expirationDate: "2027-11-22",
      },
      medCard: {
        id: "doc-d2-med",
        name: "Medical_Card_Petrovic_2026.pdf",
        category: "MEDCard",
        fileType: "application/pdf",
        fileSize: 360000,
        uploadedAt: "2025-05-14T10:00:00Z",
        expirationDate: "2027-05-14",
      },
      clearingHouse: {
        id: "doc-d2-ch",
        name: "Clearinghouse_Report_Petrovic.pdf",
        category: "Clearing House",
        fileType: "application/pdf",
        fileSize: 280000,
        uploadedAt: "2026-08-20T10:00:00Z",
      },
      applicationLink: "https://intelli-app.zdunjetrucking.com/app/a-petrovic-104",
      applicationFile: {
        id: "doc-d2-app",
        name: "Application_Petrovic.pdf",
        category: "Application Link",
        fileType: "application/pdf",
        fileSize: 760000,
        uploadedAt: "2022-08-20T10:00:00Z",
      },
      drugCustodyForm: {
        id: "doc-d2-ccf",
        name: "Custody_Control_Form_Petrovic.pdf",
        category: "Drug Test Custody Form",
        fileType: "application/pdf",
        fileSize: 410000,
        uploadedAt: "2022-08-26T14:00:00Z",
      },
      drugPassport: {
        id: "doc-d2-pass",
        name: "LabCorp_ePassport_Petrovic.pdf",
        category: "Drug Test ePassport",
        fileType: "application/pdf",
        fileSize: 230000,
        uploadedAt: "2022-08-25T15:00:00Z",
      },
      drugTestResults: [
        {
          id: "doc-d2-dt-1",
          name: "DrugTest_PreEmployment_Petrovic.pdf",
          category: "Drug Test Result",
          fileType: "application/pdf",
          fileSize: 310000,
          uploadedAt: "2022-08-28T09:00:00Z",
          testDate: "2022-08-27",
          testType: "Pre-Employment",
          notes: "Result: NEGATIVE",
        },
        {
          id: "doc-d2-dt-2",
          name: "DrugTest_Random_FMCSA_Feb2026.pdf",
          category: "Drug Test Result",
          fileType: "application/pdf",
          fileSize: 290000,
          uploadedAt: "2026-02-14T11:00:00Z",
          testDate: "2026-02-13",
          testType: "Random FMCSA",
          notes: "FMCSA monthly random pull. Result: NEGATIVE",
        },
      ],
      dotRecords: [
        {
          id: "doc-d2-dot-1",
          name: "DOT_Roadside_Inspection_Level2_Petrovic.pdf",
          category: "Driver DOT Record",
          fileType: "application/pdf",
          fileSize: 345000,
          uploadedAt: "2026-05-18T10:15:00Z",
          recordDate: "2026-05-18",
          inspectionLevel: "Level 2 (Walk-Around)",
          inspectionResult: "Clean / No Violations",
          notes: "Indiana State Police inspection post #4. Verified logbook, hours of service, coupling devices, and lights.",
        },
      ],
      bankInfoDoc: {
        id: "doc-d2-bank",
        name: "FifthThird_Voided_Check.pdf",
        category: "Bank Information",
        fileType: "application/pdf",
        fileSize: 320000,
        uploadedAt: "2022-08-30T10:00:00Z",
      },
      einLetter: {
        id: "doc-d2-ein",
        name: "EIN_Confirmation_Petrovic.pdf",
        category: "EIN Letter",
        fileType: "application/pdf",
        fileSize: 270000,
        uploadedAt: "2022-08-30T11:00:00Z",
      },
      onboardingDoc: {
        id: "doc-d2-onboard",
        name: "Onboarding_Package_Signed_Petrovic.pdf",
        category: "Onboarding Document",
        fileType: "application/pdf",
        fileSize: 490000,
        uploadedAt: "2022-09-01T08:30:00Z",
      },
      leaseAgreement: {
        id: "doc-d2-lease",
        name: "OwnerOperator_Lease_Agreement_Petrovic.pdf",
        category: "Driver Lease Agreement",
        fileType: "application/pdf",
        fileSize: 620000,
        uploadedAt: "2022-09-01T09:00:00Z",
        expirationDate: "2027-09-01",
        notes: "Independent Contractor Agreement - 88% gross revenue split",
      },
    },
    skippedDocuments: [],
  },
  {
    id: "driver-3",
    firstName: "Marcus",
    middleName: "Vance",
    lastName: "Williams",
    dateOfBirth: "1991-03-08",
    phone: "(614) 555-0177",
    state: "OH",
    licenseNumber: "OH-TL9910481",
    status: "Active",
    assignedTruckId: null,
    hireDate: "2024-01-15",
    notes: "Available for assignment to Unit 107 once truck exits maintenance.",
    bankInfo: {
      accountNumber: "5519201948",
      routingNumber: "044000037",
      bankName: "Huntington National Bank",
    },
    documents: {
      mvr: {
        id: "doc-d3-mvr",
        name: "Ohio_MVR_Williams.pdf",
        category: "MVR",
        fileType: "application/pdf",
        fileSize: 310000,
        uploadedAt: "2026-01-10T10:00:00Z",
      },
      pspAuth: {
        id: "doc-d3-pspauth",
        name: "PSP_Consent_Williams.pdf",
        category: "PSP Authorization",
        fileType: "application/pdf",
        fileSize: 200000,
        uploadedAt: "2024-01-10T10:00:00Z",
      },
      pspReport: {
        id: "doc-d3-psprep",
        name: "PSP_Report_Williams.pdf",
        category: "PSP Driver Report",
        fileType: "application/pdf",
        fileSize: 420000,
        uploadedAt: "2026-01-12T11:00:00Z",
      },
      cdl: {
        id: "doc-d3-cdl",
        name: "CDL_ClassA_Williams_OH.pdf",
        category: "CDL",
        fileType: "application/pdf",
        fileSize: 510000,
        uploadedAt: "2024-01-10T10:00:00Z",
        expirationDate: "2027-03-08",
      },
      medCard: {
        id: "doc-d3-med",
        name: "DOT_Medical_Card_Williams.pdf",
        category: "MEDCard",
        fileType: "application/pdf",
        fileSize: 350000,
        uploadedAt: "2025-01-05T09:00:00Z",
        expirationDate: "2027-01-05",
      },
      clearingHouse: {
        id: "doc-d3-ch",
        name: "Clearinghouse_Query_Williams.pdf",
        category: "Clearing House",
        fileType: "application/pdf",
        fileSize: 275000,
        uploadedAt: "2026-01-14T10:00:00Z",
      },
      applicationLink: "https://intelli-app.zdunjetrucking.com/app/m-williams-107",
      applicationFile: {
        id: "doc-d3-app",
        name: "Application_Williams.pdf",
        category: "Application Link",
        fileType: "application/pdf",
        fileSize: 730000,
        uploadedAt: "2024-01-08T10:00:00Z",
      },
      drugCustodyForm: {
        id: "doc-d3-ccf",
        name: "Drug_Custody_Williams.pdf",
        category: "Drug Test Custody Form",
        fileType: "application/pdf",
        fileSize: 395000,
        uploadedAt: "2024-01-11T12:00:00Z",
      },
      drugPassport: {
        id: "doc-d3-pass",
        name: "Quest_Passport_Williams.pdf",
        category: "Drug Test ePassport",
        fileType: "application/pdf",
        fileSize: 215000,
        uploadedAt: "2024-01-10T14:00:00Z",
      },
      drugTestResults: [
        {
          id: "doc-d3-dt-1",
          name: "DrugTest_PreEmployment_Williams.pdf",
          category: "Drug Test Result",
          fileType: "application/pdf",
          fileSize: 320000,
          uploadedAt: "2024-01-13T10:00:00Z",
          testDate: "2024-01-12",
          testType: "Pre-Employment",
          notes: "Result: NEGATIVE",
        },
      ],
      dotRecords: [],
      bankInfoDoc: {
        id: "doc-d3-bank",
        name: "DirectDeposit_Huntington_Williams.pdf",
        category: "Bank Information",
        fileType: "application/pdf",
        fileSize: 300000,
        uploadedAt: "2024-01-15T10:00:00Z",
      },
      einLetter: {
        id: "doc-d3-ein",
        name: "EIN_Letter_Williams.pdf",
        category: "EIN Letter",
        fileType: "application/pdf",
        fileSize: 265000,
        uploadedAt: "2024-01-15T11:00:00Z",
      },
      onboardingDoc: null, // Missing!
      leaseAgreement: null, // Skipped
    },
    skippedDocuments: ["leaseAgreement"],
  },
];

export const initialShops: TruckShop[] = [
  {
    id: "shop-1",
    businessName: "TA Truck Service - Lake Station #082",
    businessAddress: "1201 Ripon Dr, Lake Station, IN 46405",
    state: "IN",
    phone: "(219) 962-9511",
    shopType: "Both",
    repairCategories: [
      "Tires & Alignment",
      "PM-A (Oil & Lube)",
      "Brakes & Air System",
      "Electrical & Lights",
      "DOT Annual Inspection",
      "Roadside Service",
    ],
    descriptionOfWork:
      "Full 12-bay diesel repair facility with 24/7 RoadSquad dispatch. Certified Cummins & Detroit Diesel mechanics, Hunter heavy-duty laser alignment, complete tire bank (Bridgestone, Michelin, Goodyear).",
    googleMapsUrl: "https://maps.google.com/?q=TA+Truck+Service+Lake+Station+IN",
    laborRatePerHour: 145,
    calloutFee: 175,
    rating: 5,
    notes: "Main preferred shop for Northern Indiana / Chicago corridor. Speak with Dave (Shop Foreman).",
  },
  {
    id: "shop-2",
    businessName: "Love's Truck Care - Effingham #401",
    businessAddress: "1800 W Fayette Ave, Effingham, IL 62401",
    state: "IL",
    phone: "(217) 347-7104",
    shopType: "Both",
    repairCategories: [
      "Tires & Alignment",
      "PM-A (Oil & Lube)",
      "Brakes & Air System",
      "Electrical & Lights",
      "Roadside Emergency",
    ],
    descriptionOfWork:
      "24-hour truck tire repair, light mechanical, wheel-end seals, air brake chambers, and scheduled oil/lube maintenance.",
    googleMapsUrl: "https://maps.google.com/?q=Loves+Truck+Care+Effingham+IL",
    laborRatePerHour: 135,
    calloutFee: 150,
    rating: 4,
    notes: "Great tire replacement speed on I-57 / I-70 junction.",
  },
  {
    id: "shop-3",
    businessName: "24/7 Mobile Fleet Heavy Duty Roadside",
    businessAddress: "5200 E 5th Ave, Gary, IN 46403",
    state: "IN",
    phone: "(219) 555-0199",
    shopType: "Roadside",
    repairCategories: [
      "Roadside Emergency",
      "Tires & Alignment",
      "Brakes & Air System",
      "Engine & Transmission",
      "Exhaust & Emissions (DPF)",
      "Jump Starts & Fuel Delivery",
    ],
    descriptionOfWork:
      "Dedicated heavy-duty mobile response units equipped with air compressors, computerized diagnostic laptops, brake chambers, and emergency tire inventory. Average response time under 45 minutes on I-80/94.",
    googleMapsUrl: "https://maps.google.com/?q=Gary+IN+Roadside+Service",
    laborRatePerHour: 165,
    calloutFee: 195,
    rating: 5,
    notes: "Top pick for night-time breakdowns in Northwest Indiana / Gary / Hammond corridor.",
  },
  {
    id: "shop-4",
    businessName: "Rush Truck Center - Chicago Central",
    businessAddress: "3900 S Normal Ave, Chicago, IL 60609",
    state: "IL",
    phone: "(773) 843-8500",
    shopType: "Shop",
    repairCategories: [
      "Engine & Transmission",
      "Exhaust & Emissions (DPF)",
      "PM-B (Full Inspection)",
      "PM-C (Major Overhaul)",
      "Electrical & Lights",
      "Annual DOT Inspection",
    ],
    descriptionOfWork:
      "OEM Peterbilt, Navistar, and Cummins certified warranty & major repair center. Complete dynamometer, DPF cleaning oven, and transmission rebuild facility.",
    googleMapsUrl: "https://maps.google.com/?q=Rush+Truck+Center+Chicago+IL",
    laborRatePerHour: 185,
    calloutFee: 0,
    rating: 4,
    notes: "Use for warranty claims and major engine/transmission repairs.",
  },
];

export const initialMaintenanceRecords: MaintenanceRecord[] = [
  {
    id: "maint-1",
    truckId: "truck-101",
    truckUnitNumber: "101",
    serviceDate: "2026-08-15",
    odometer: 138200,
    serviceType: "PM-A (Oil & Lube)",
    shopId: "shop-1",
    shopName: "TA Truck Service - Lake Station #082",
    laborCost: 190,
    partsCost: 340,
    calloutFee: 0,
    totalCost: 530,
    invoiceNumber: "INV-TA-992014",
    nextServiceDueMileage: 153200,
    nextServiceDueDate: "2026-11-15",
    status: "Completed",
    description:
      "Standard PM-A service: 15W-40 Shell Rotella T6 synthetic oil change (11 gallons), 2 oil filters replaced, fuel/water separator replaced, 24 grease points lubricated, air cleaner inspected.",
    invoiceDocument: {
      id: "doc-inv-1",
      name: "Invoice_TA_LakeStation_101.pdf",
      category: "Maintenance Invoice",
      fileType: "application/pdf",
      fileSize: 410000,
      uploadedAt: "2026-08-15T18:00:00Z",
    },
  },
  {
    id: "maint-2",
    truckId: "truck-104",
    truckUnitNumber: "104",
    serviceDate: "2026-09-02",
    odometer: 186400,
    serviceType: "Tires & Alignment",
    shopId: "shop-2",
    shopName: "Love's Truck Care - Effingham #401",
    laborCost: 220,
    partsCost: 1180,
    calloutFee: 0,
    totalCost: 1400,
    invoiceNumber: "INV-LOV-44109",
    nextServiceDueMileage: 216400,
    nextServiceDueDate: "2027-03-01",
    status: "Completed",
    description:
      "Replaced two front steer tires with Bridgestone R284 Ecopia (295/75R22.5). Performed computerized 3-axle front steer alignment and balanced both wheels.",
    invoiceDocument: {
      id: "doc-inv-2",
      name: "Invoice_SteerTires_104.pdf",
      category: "Maintenance Invoice",
      fileType: "application/pdf",
      fileSize: 380000,
      uploadedAt: "2026-09-02T16:00:00Z",
    },
  },
  {
    id: "maint-3",
    truckId: "truck-107",
    truckUnitNumber: "107",
    serviceDate: "2026-09-26",
    odometer: 46200,
    serviceType: "PM-B (Full Inspection)",
    shopId: "shop-4",
    shopName: "Rush Truck Center - Chicago Central",
    laborCost: 450,
    partsCost: 520,
    calloutFee: 0,
    totalCost: 970,
    invoiceNumber: "INV-RUSH-2026-881",
    nextServiceDueMileage: 61200,
    nextServiceDueDate: "2026-12-26",
    status: "In Progress",
    description:
      "45,000-mile comprehensive OEM inspection: complete fluid exchange, valve lash check, CAC pressure test, DPF differential pressure check, brake pad measurement, BestPass transponder bracket mount.",
  },
  {
    id: "maint-4",
    truckId: "truck-101",
    truckUnitNumber: "101",
    serviceDate: "2026-07-20",
    odometer: 132400,
    serviceType: "Roadside Emergency",
    shopId: "shop-3",
    shopName: "24/7 Mobile Fleet Heavy Duty Roadside",
    laborCost: 240,
    partsCost: 165,
    calloutFee: 195,
    totalCost: 600,
    invoiceNumber: "INV-247-8192",
    status: "Completed",
    description:
      "Emergency callout on I-80 Mile Marker 15 eastbound: blown trailer air line gladhand seal and cracked quick-release valve replaced. Pressure tested to 125 PSI with zero leaks.",
  },
];
